# Generated by Django 4.1.1 on 2022-10-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Switch',
        ),
    ]
